version: '3'
services:
  nginx:
    build: ./nginx
    volumes:
      - ./flontend/view:/usr/src/view
    command: ["nginx", "-g", "daemon off;"]
    restart: always
    ports:
      - "30080:80"
      - "30443:443"
  flontend:
    build: ./flontend
    environment:
      - NODE_ENV=development
    volumes:
      - ./flontend/ts:/usr/src/ts
      - ./flontend/html:/usr/src/html
      - ./flontend/view:/usr/src/view
      - ./flontend/package.json:/usr/src/package.json
      - ./flontend/tsconfig.json:/usr/src/tsconfig.json
      - ./flontend/nodemon.json:/usr/src/nodemon.json
      - ./flontend/build.js:/usr/src/build.js
      - ./flontend/biome.json:/usr/src/biome.json
    command: bash -c "npm run dev"
    restart: always
  python:
    build: ./python
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    working_dir: /api/app
    volumes:
      - ./python:/api/app
      # - ./flontend/view:/api/view
      - ./.vscode:/api/.vscode
    restart: always
